#!/bin/bash

#membersihkan tampilan layar
#clear

#variabel

sshd=`systemctl status ssh | grep -e "Active:"`;
httpd=`systemctl status apache2 | grep -e "Active:"`;
mysql=`systemctl status mysql | grep -e "Active:"`;
#tes1=`echo "anjay"`;

#output
echo -e "STATUS SSH";
echo $sshd;
#systemctl status ssh
echo -e "\n STATUS HTTPD"
echo $httpd;
echo -e "\n STATUS MYSQL"
echo $mysql;

