#!/bin/bash

#Jawaban dengan menggunakan positional parameter

echo -e `STATUS $1 \n`;
systemctl status $1;

#Percobaan dengan menggunakan user defined variable

#sshd=`systemctl status ssh | grep -e "Active:"`;
#httpd=`systemctl status apache2 | grep -e "Active:"`;
#mysql=`systemctl status mysql | grep -e "Active:"`;

#output
#echo -e "STATUS SSH";
#echo $sshd;
#systemctl status ssh
#echo -e "\n STATUS HTTPD"
#echo $httpd;
#echo -e "\n STATUS MYSQL"
#echo $mysql;

